# Generated by Django 3.0.2 on 2020-01-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
